# frozen_string_literal: true

module Plurimath
  class Latex
    class Constants
      UNARY_CLASSES = %w[
        overline
        substack
        arccos
        arcsin
        arctan
        limsup
        liminf
        sinh
        coth
        tanh
        cosh
        tan
        cos
        cot
        csc
        deg
        det
        dim
        exp
        gcd
        max
        min
        sec
        sin
        hom
        sup
        ker
        lg
        ln
      ].freeze
      ENVIRONMENTS = {
        "pmatrix" => "(",
        "bmatrix" => "[",
        "Bmatrix" => "{",
        "vmatrix" => "|",
        "Vmatrix" => "norm[",
        "matrix" => nil,
        "split" => nil,
        "array" => nil,
      }.freeze
      SYMBOLS = %w[
        leftrightharpoondowndown
        shortrightarrowleftarrow
        leftarrowshortrightarrow
        rightarrowshortleftarrow
        barleftarrowrightarrowba
        downupharpoonsleftright
        updownharpoonsleftright
        updownharpoonrightright
        nVtwoheadrightarrowtail
        nvtwoheadrightarrowtail
        concavediamondtickright
        invwhitelowerhalfcircle
        invwhiteupperhalfcircle
        smallblacktriangleright
        nVtwoheadleftarrowtail
        nvtwoheadleftarrowtail
        partialmeetcontraction
        downtrianglerightblack
        updownharpoonleftright
        updownharpoonrightleft
        leftrightharpoondownup
        leftrightharpoonupdown
        concavediamondtickleft
        blackcircleulquadwhite
        smallblacktriangleleft
        leftrightarrowtriangle
        closedvarcupsmashprod
        blackdiamonddownarrow
        downtriangleleftblack
        rightleftharpoonsdown
        leftrightharpoonsdown
        downharpoonsleftright
        updownharpoonleftleft
        twoheadrightarrowtail
        circlebottomhalfblack
        rangledownzigzagarrow
        barovernorthwestarrow
        underrightharpoondown
        rightarrowbackapprox
        twoheadleftarrowtail
        NestedGreaterGreater
        blackcircledownarrow
        dashrightharpoondown
        leftrightharpoondown
        leftrightharpoonupup
        twoheaduparrowcircle
        leftrightarrowcircle
        curvearrowrightminus
        rightdowncurvedarrow
        downrightcurvedarrow
        barrightarrowdiamond
        whitesquaretickright
        whiteinwhitetriangle
        blackcircledrightdot
        blackrighthalfcircle
        circlerighthalfblack
        bigblacktriangledown
        CapitalDifferentialD
        underleftharpoondown
        leftarrowbackapprox
        twoheadleftdbkarrow
        dashleftharpoondown
        rightleftharpoonsup
        leftrightharpoonsup
        rightharpoonsupdown
        upharpoonsleftright
        barrightharpoondown
        bardownharpoonright
        rightharpoondownbar
        downharpoonrightbar
        leftdowncurvedarrow
        diamondleftarrowbar
        nVtwoheadrightarrow
        nvtwoheadrightarrow
        longrightsquigarrow
        whitesquaretickleft
        blackcircledtwodots
        blacklefthalfcircle
        circlelefthalfblack
        blackinwhitediamond
        blockthreeqtrshaded
        whitearrowupfrombar
        leftrightsquigarrow
        rightpentagonblack
        bsimilarrightarrow
        rightarrowbsimilar
        nVtwoheadleftarrow
        nvtwoheadleftarrow
        longleftsquigarrow
        errbarblackdiamond
        circledwhitebullet
        rightharpoonupdash
        rightrightharpoons
        leftharpoonsupdown
        bardownharpoonleft
        DownRightTeeVector
        leftharpoondownbar
        RightDownTeeVector
        downharpoonleftbar
        DownRightVectorBar
        barleftharpoondown
        RightDownVectorBar
        rightupdownharpoon
        leftrightharpoonup
        ccwundercurvearrow
        curvearrowleftplus
        Longleftrightarrow
        longleftrightarrow
        trianglerightblack
        inversewhitecircle
        circletophalfblack
        smalltriangleright
        blacktriangleright
        bigblacktriangleup
        parallelogramblack
        blackinwhitesquare
        measuredrightangle
        SucceedsSlantEqual
        PrecedesSlantEqual
        rightarrowtriangle
        circleonrightarrow
        upharpoonrightdown
        acwopencirclearrow
        overleftrightarrow
        rightharpoonaccent
        bsimilarleftarrow
        leftarrowbsimilar
        circleonleftarrow
        diamondrightblack
        errbarblackcircle
        errbarblacksquare
        measuredangleleft
        rightarrowsimilar
        similarrightarrow
        leftharpoonupdash
        LeftDownTeeVector
        DownLeftTeeVector
        upharpoonrightbar
        barrightharpoonup
        LeftDownVectorBar
        DownLeftVectorBar
        barupharpoonright
        rightharpoonupbar
        leftupdownharpoon
        cwundercurvearrow
        uprightcurvearrow
        rightarrowdiamond
        rightarrowonoplus
        acwgapcirclearrow
        triangleleftblack
        circleurquadblack
        smalltriangleleft
        blacktriangleleft
        smalltriangledown
        blacktriangledown
        whitepointerright
        blackpointerright
        varcarriagereturn
        varhexagonlrbonds
        vardoublebarwedge
        kernelcontraction
        leftarrowtriangle
        rightleftharpoons
        leftrightharpoons
        upharpoonleftdown
        cwopencirclearrow
        twoheadrightarrow
        leftharpoonaccent
        similarleftarrow
        rightarrowsupset
        leftarrowonoplus
        diamondleftblack
        RightTriangleBar
        sphericalangleup
        rightarrowapprox
        leftarrowsimilar
        uprevequilibrium
        downdownharpoons
        leftleftharpoons
        upharpoonleftbar
        RightUpTeeVector
        leftharpoonupbar
        barupharpoonleft
        RightUpVectorBar
        barleftharpoonup
        rightleftharpoon
        leftrightharpoon
        acwunderarcarrow
        rightcurvedarrow
        diamondleftarrow
        nVrightarrowtail
        nvrightarrowtail
        nvLeftrightarrow
        cwgapcirclearrow
        squarerightblack
        whitepointerleft
        blackpointerleft
        APLrightarrowbox
        ntrianglerighteq
        NotRightTriangle
        multimapdotbothB
        multimapdotbothA
        vartriangleright
        ointctrclockwise
        varointclockwise
        nVleftrightarrow
        nvleftrightarrow
        rightthreearrows
        downarrowuparrow
        rightrightarrows
        uparrowdownarrow
        downharpoonright
        rightharpoondown
        circlearrowright
        twoheaddownarrow
        twoheadleftarrow
        leftarrowapprox
        leftcurvedarrow
        nVleftarrowtail
        nvleftarrowtail
        twoheadmapsfrom
        leftthreearrows
        varhexagonblack
        diamondbotblack
        diamondtopblack
        bigtriangleleft
        circledownarrow
        LeftTriangleBar
        uparrowoncircle
        circledparallel
        measangledltosw
        measangledrtose
        measangleultonw
        measangleurtone
        measangleldtosw
        measanglerdtose
        measanglelutonw
        measanglerutone
        leftarrowsubset
        equalrightarrow
        barrightharpoon
        rightbarharpoon
        LeftUpTeeVector
        LeftUpVectorBar
        acwoverarcarrow
        acwleftarcarrow
        cwrightarcarrow
        downarrowbarred
        circledrightdot
        squareleftblack
        urblacktriangle
        ulblacktriangle
        llblacktriangle
        lrblacktriangle
        bigtriangledown
        smalltriangleup
        blacktriangleup
        vrectangleblack
        hrectangleblack
        squarecrossfill
        blockhalfshaded
        APLdownarrowbox
        APLleftarrowbox
        APLnotbackslash
        ntrianglelefteq
        NotLeftTriangle
        rightthreetimes
        trianglerighteq
        vartriangleleft
        NotGreaterTilde
        rightwhitearrow
        rightsquigarrow
        nLeftrightarrow
        leftrightarrows
        rightleftarrows
        downharpoonleft
        upharpoonleftup
        leftharpoondown
        circlearrowleft
        curvearrowright
        downzigzagarrow
        nleftrightarrow
        underrightarrow
        widebridgeabove
        enclosetriangle
        unicodeellipsis
        enleadertwodots
        equalleftarrow
        squarebotblack
        squaretopblack
        NestedLessLess
        wedgedoublebar
        doublebarwedge
        bigslopedwedge
        mdlgblklozenge
        blackhourglass
        triangleserifs
        rightanglemdot
        downupharpoons
        updownharpoons
        barleftharpoon
        leftbarharpoon
        RightTeeVector
        RightVectorBar
        rightarrowplus
        acwcirclearrow
        rdiagovsearrow
        fdiagovnearrow
        Longmappedfrom
        longmappedfrom
        Longrightarrow
        longrightarrow
        concavediamond
        rightouterjoin
        circledtwodots
        vardiamondsuit
        circlevertfill
        mdlgwhtlozenge
        mdlgwhtdiamond
        mdlgblkdiamond
        squareneswfill
        squarenwsefill
        blockqtrshaded
        blockrighthalf
        harrowextender
        vbraceextender
        rbrackextender
        lbrackextender
        rparenextender
        lparenextender
        APLboxquestion
        ntriangleright
        leftthreetimes
        trianglelefteq
        NotGreaterLess
        sphericalangle
        downwhitearrow
        leftwhitearrow
        rightdasharrow
        dashrightarrow
        leftsquigarrow
        Leftrightarrow
        revequilibrium
        downdownarrows
        leftleftarrows
        rightleftarrow
        rightharpoonup
        upharpoonright
        curvearrowleft
        carriagereturn
        looparrowright
        hookrightarrow
        updownarrowbar
        rightarrowtail
        twoheaduparrow
        rightwavearrow
        leftrightarrow
        underleftarrow
        enclosediamond
        ocommatopright
        rightpentagon
        rightarrowgtr
        pentagonblack
        vysmwhtsquare
        vysmblksquare
        squarellblack
        squareurblack
        bigtalloblong
        biginterleave
        threedotcolon
        shortdowntack
        shortlefttack
        triangletimes
        triangleminus
        errbardiamond
        circledbullet
        circledbslash
        emptysetoarrl
        emptysetocirc
        wideangledown
        rightanglesqr
        rrparenthesis
        llparenthesis
        mdsmblkcircle
        rightfishtail
        leftarrowless
        upequilibrium
        LeftTeeVector
        LeftVectorBar
        leftarrowplus
        cwcirclearrow
        rightdotarrow
        uparrowbarred
        twoheadmapsto
        Longleftarrow
        longleftarrow
        fullouterjoin
        leftouterjoin
        draftingarrow
        mdsmwhtcircle
        Hermaphrodite
        sixteenthnote
        mdsmblksquare
        mdsmwhtsquare
        squarelrblack
        squareulblack
        botsemicircle
        topsemicircle
        inversebullet
        mdlgblkcircle
        mdlgwhtcircle
        triangleright
        blacktriangle
        bigtriangleup
        parallelogram
        mdlgwhtsquare
        mdlgblksquare
        blocklefthalf
        bdtriplevdash
        APLboxupcaret
        APLuparrowbox
        ntriangleleft
        equalparallel
        divideontimes
        varlrtriangle
        SucceedsTilde
        PrecedesTilde
        fallingdotseq
        dotsminusdots
        wasytherefore
        measuredangle
        vysmblkcircle
        vysmwhtcircle
        smallsetminus
        rightarrowbar
        RightArrowBar
        downdasharrow
        leftdasharrow
        dashleftarrow
        upharpoonleft
        leftharpoonup
        looparrowleft
        hookleftarrow
        leftarrowtail
        leftwavearrow
        DifferentialD
        sansLmirrored
        threeunderdot
        enclosesquare
        enclosecircle
        overleftarrow
        upbackepsilon
        medblackstar
        medwhitestar
        leftdotarrow
        smwhtlozenge
        smblklozenge
        smblkdiamond
        mdwhtlozenge
        mdblklozenge
        mdwhtdiamond
        mdblkdiamond
        hexagonblack
        dottedsquare
        supsetapprox
        subsetapprox
        eqqslantless
        veedoublebar
        doublebarvee
        wedgemidvert
        bigslopedvee
        wedgeonwedge
        closedvarcap
        closedvarcup
        triangleplus
        errbarcircle
        errbarsquare
        blacklozenge
        lrtriangleeq
        multimapboth
        triangleubar
        triangleodot
        ogreaterthan
        odotslashdot
        emptysetoarr
        emptysetobar
        revangleubar
        rbrackurtick
        lbracklltick
        rbracklrtick
        lbrackultick
        downfishtail
        leftfishtail
        upupharpoons
        fdiagovrdiag
        rdiagovfdiag
        rightdbltail
        downarrowbar
        DownArrowBar
        leftdbkarrow
        rightbkarrow
        nvRightarrow
        Longmapsfrom
        longmapsfrom
        lozengeminus
        longdivision
        dingasterisk
        varheartsuit
        varspadesuit
        invsmileface
        bigwhitestar
        circleurquad
        circlelrquad
        circlellquad
        circleulquad
        squareurquad
        squarelrquad
        squarellquad
        squareulquad
        trianglecdot
        dottedcircle
        Diamondblack
        triangleleft
        triangledown
        squarehvfill
        blocklowhalf
        underbracket
        notbackslash
        unicodecdots
        nsucccurlyeq
        npreccurlyeq
        smwhtdiamond
        hermitmatrix
        circledequal
        cupleftarrow
        varsubsetneq
        NotLessTilde
        risingdotseq
        cntclockoint
        intclockwise
        nVrightarrow
        nvrightarrow
        downuparrows
        upwhitearrow
        barleftarrow
        LeftArrowBar
        updownarrows
        PropertyLine
        hyphenbullet
        upvarepsilon
        oturnedcomma
        mathsterling
        RRightarrow
        smwhitestar
        whtvertoval
        blkvertoval
        whthorzoval
        blkhorzoval
        lgblkcircle
        lgwhtsquare
        lgblksquare
        shortuptack
        succnapprox
        precnapprox
        eqqslantgtr
        eqslantless
        simminussim
        midbarwedge
        otimesrhrim
        otimeslhrim
        rcurvyangle
        lcurvyangle
        ruledelayed
        gleichstark
        circledless
        circledvert
        revemptyset
        wideangleup
        rightarrowx
        nwovnearrow
        neovnwarrow
        neovsearrow
        seovnearrow
        leftdbltail
        leftbkarrow
        nvLeftarrow
        multimapinv
        diamondcdot
        threedangle
        arrowbullet
        circledstar
        ballotcheck
        mdblkcircle
        mdwhtcircle
        quarternote
        varclubsuit
        diamondsuit
        capricornus
        sagittarius
        blacksmiley
        mdblksquare
        blacksquare
        mdwhtsquare
        lgwhtcircle
        smwhtcircle
        RIGHTCIRCLE
        RIGHTcircle
        vartriangle
        smwhtsquare
        smblksquare
        squarevfill
        squarehfill
        blockuphalf
        overbracket
        intextender
        invdiameter
        APLnotslash
        wasylozenge
        varbarwedge
        varisinobar
        sqsupsetneq
        sqsubsetneq
        nsqsupseteq
        nsqsubseteq
        curlyeqsucc
        curlyeqprec
        circleddash
        circledcirc
        succcurlyeq
        preccurlyeq
        GreaterLess
        corresponds
        approxident
        nVleftarrow
        nvleftarrow
        updasharrow
        nHdownarrow
        Rrightarrow
        Updownarrow
        nRightarrow
        equilibrium
        restriction
        nrightarrow
        updownarrow
        ExponetialE
        sansLturned
        Planckconst
        asteraccent
        vertoverlay
        caretinsert
        backtrprime
        smblkcircle
        backepsilon
        postalmark
        LLeftarrow
        leftarrowx
        varhexagon
        talloblong
        interleave
        supsetneqq
        subsetneqq
        supsetplus
        subsetplus
        succapprox
        precapprox
        rightslice
        eqslantgtr
        gtreqqless
        lesseqqgtr
        lessapprox
        equivVvert
        veemidvert
        veeonwedge
        capovercup
        cupovercap
        smashtimes
        oplusrhrim
        opluslhrim
        minusrdots
        minusfdots
        commaminus
        plussubtwo
        tripleplus
        doubleplus
        circledgtr
        circlehbar
        rblkbrbrak
        lblkbrbrak
        Rparenless
        lparenless
        rbrackubar
        lbrackubar
        upfishtail
        rightimply
        baruparrow
        UpArrowBar
        Ddownarrow
        Mappedfrom
        Longmapsto
        longmapsto
        DDownarrow
        Diamonddot
        supsetcirc
        subsetcirc
        eighthnote
        vardiamond
        pointright
        CheckedBox
        lrtriangle
        lltriangle
        urtriangle
        ultriangle
        LEFTCIRCLE
        LEFTcircle
        vrectangle
        hrectangle
        underbrace
        underparen
        rmoustache
        lmoustache
        rbracelend
        rbraceuend
        lbracelend
        lbraceuend
        rbracklend
        rbrackuend
        lbracklend
        lbrackuend
        rparenlend
        rparenuend
        lparenlend
        lparenuend
        APLcomment
        conictaper
        curlywedge
        circledast
        sqsupseteq
        sqsubseteq
        Proportion
        rightangle
        fourthroot
        varnothing
        complement
        Lleftarrow
        Rightarrow
        nLeftarrow
        upuparrows
        mappedfrom
        nleftarrow
        rightarrow
        turnediota
        Eulerconst
        backdprime
        twolowline
        upvarTheta
        upvarkappa
        upoldkoppa
        upoldKoppa
        upvartheta
        upvarsigma
        varepsilon
        wideutilde
        mathdollar
        octothorpe
        geqqslant
        leqqslant
        supseteqq
        subseteqq
        supsetdot
        subsetdot
        leftslice
        gtrapprox
        approxeqq
        hatapprox
        equivVert
        varveebar
        midbarvee
        wedgeodot
        capbarcup
        cupbarcap
        otimeshat
        modtwosum
        disjquant
        conjquant
        bigcupdot
        bigotimes
        hourglass
        triangles
        boxcircle
        boxbslash
        olessthan
        angleubar
        turnangle
        fourvdots
        Lparengtr
        rparengtr
        rangledot
        langledot
        typecolon
        hknearrow
        hknwarrow
        neswarrow
        nwsearrow
        righttail
        impliedby
        rrbracket
        llbracket
        longdashv
        vlongdash
        dashVdash
        DashVDash
        checkmark
        medbullet
        heartsuit
        spadesuit
        rightmoon
        smileface
        biohazard
        radiation
        blockfull
        accurrent
        trapezium
        overbrace
        wideparen
        overparen
        rvboxline
        lvboxline
        sumbottom
        rbracemid
        lbracemid
        intbottom
        turnednot
        sqlozenge
        bagmember
        varniobar
        gtreqless
        lesseqgtr
        pitchfork
        backsimeq
        supsetneq
        subsetneq
        nsupseteq
        nsubseteq
        ngeqslant
        nleqslant
        triangleq
        dashcolon
        mathratio
        therefore
        clockoint
        nparallel
        increment
        partialup
        dasharrow
        nHuparrow
        Downarrow
        Leftarrow
        rightturn
        lightning
        downarrow
        leftarrow
        Angstroem
        fracslash
        tieconcat
        backprime
        updigamma
        upDigamma
        upvarbeta
        upupsilon
        upomicron
        upepsilon
        upUpsilon
        upOmicron
        upEpsilon
        underline
        backslash
        semicolon
        mathcolon
        mathslash
        ampersand
        pentagon
        varVdash
        forksnot
        succneqq
        precneqq
        gnapprox
        lnapprox
        gesdotol
        lesdotor
        geqslant
        leqslant
        Coloneqq
        simrdots
        dotequiv
        wedgebar
        veeonvee
        capwedge
        intprodr
        timesbar
        dottimes
        vectimes
        minusdot
        plustrif
        ringplus
        zproject
        intlarhk
        pointint
        scpolint
        rppolint
        cirfnint
        bigtimes
        bigsqcup
        bigsqcap
        biguplus
        bigoplus
        setminus
        eqvparsl
        smeparsl
        tieinfty
        Rvzigzag
        Lvzigzag
        rvzigzag
        lvzigzag
        rfbowtie
        lfbowtie
        rtriltri
        boxonbox
        boxslash
        revangle
        strictif
        strictfi
        hkswarow
        hksearow
        lefttail
        drbkarow
        Uuparrow
        Mapsfrom
        UUparrow
        pullback
        wedgedot
        bsolhsub
        acidfree
        twonotes
        varheart
        varspade
        clubsuit
        aquarius
        varEarth
        leftmoon
        steaming
        astrosun
        bullseye
        triangle
        elinters
        bbrktbrk
        APLinput
        notslash
        lrcorner
        llcorner
        urcorner
        ulcorner
        viewdata
        profsurf
        profline
        diameter
        isinobar
        varisins
        succnsim
        precnsim
        curlyvee
        bigwedge
        barwedge
        intercal
        multimap
        boxtimes
        boxminus
        sqsupset
        sqsubset
        supseteq
        subseteq
        ngtrless
        nlessgtr
        nlesssim
        notasymp
        eqqcolon
        coloneqq
        doteqdot
        dotequal
        backcong
        approxeq
        sinewave
        invlazys
        dotminus
        parallel
        cuberoot
        divslash
        leftturn
        linefeed
        mapsdown
        MapsDown
        mapsfrom
        ComplexJ
        ComplexI
        Angstrom
        medspace
        Question
        horizbar
        upvarrho
        varkappa
        upstigma
        upStigma
        vartheta
        upvarphi
        varsigma
        uplambda
        upLambda
        underbar
        mathring
        circledR
        sterling
        mathcent
        question
        hzigzag
        trslash
        gggnest
        lllnest
        nhVvert
        revnmid
        topfork
        supdsub
        suphsub
        rsqhook
        lsqhook
        supedot
        subedot
        supmult
        submult
        ggcurly
        llcurly
        succeqq
        preceqq
        succneq
        precneq
        bumpeqq
        simless
        eqqless
        gesdoto
        lesdoto
        gtquest
        ltquest
        equivDD
        ddotseq
        Coloneq
        pluseqq
        eqqplus
        congdot
        veeodot
        twocaps
        twocups
        intprod
        plussim
        plusdot
        simplus
        plushat
        project
        npolint
        varprod
        bigodot
        rsolbar
        thermod
        shuffle
        dualmap
        nvinfty
        rftimes
        lftimes
        fbowtie
        boxdiag
        cirscir
        olcross
        obslash
        vzigzag
        rrangle
        llangle
        suplarr
        subrarr
        leadsto
        dbkarow
        implies
        Rbrbrak
        Lbrbrak
        pushout
        suphsol
        rbrbrak
        lbrbrak
        varstar
        maltese
        ballotx
        medcirc
        warning
        diceiii
        recycle
        natural
        varclub
        Scorpio
        scorpio
        Neptune
        neptune
        Jupiter
        jupiter
        Mercury
        mercury
        sadface
        frownie
        yinyang
        bigstar
        lozenge
        fisheye
        Diamond
        squoval
        benzenr
        ubrbrak
        obrbrak
        hexagon
        isindot
        nsucceq
        npreceq
        lessdot
        lrtimes
        diamond
        imageof
        boxplus
        nsupset
        nsubset
        succsim
        precsim
        gtrless
        lessgtr
        ngtrsim
        lesssim
        between
        questeq
        varsdef
        coloneq
        napprox
        simneqq
        backsim
        eqcolon
        because
        dbloint
        dotplus
        smallni
        smallin
        nexists
        partial
        Swarrow
        Searrow
        Nearrow
        Nwarrow
        Uparrow
        swarrow
        searrow
        nearrow
        nwarrow
        uparrow
        annuity
        closure
        trprime
        ddagger
        epsilon
        upsampi
        upSampi
        upkoppa
        upKoppa
        digamma
        Digamma
        upvarpi
        varbeta
        upomega
        upsilon
        upsigma
        upkappa
        uptheta
        updelta
        upgamma
        upalpha
        upOmega
        Upsilon
        upSigma
        upKappa
        upTheta
        upDelta
        upGamma
        upAlpha
        overbar
        matheth
        sptilde
        greater
        percent
        sslash
        parsim
        topcir
        midcir
        cirmid
        vDdash
        supsup
        subsub
        supsub
        subsup
        supsim
        subsim
        succeq
        preceq
        simgtr
        eqqgtr
        egsdot
        elsdot
        gesles
        lesges
        gesdot
        lesdot
        eqeqeq
        eqqsim
        dotsim
        cupvee
        barcap
        barcup
        uminus
        capdot
        Otimes
        btimes
        lowint
        intcup
        intcap
        sqrint
        intBar
        intbar
        iiiint
        sumint
        tminus
        eparsl
        laplac
        iinfin
        vbrtri
        ltrivb
        boxbox
        boxast
        gtlpar
        angdnr
        angles
        rParen
        Rparen
        lParen
        Lparen
        rBrace
        lBrace
        gtrarr
        ltlarr
        Mapsto
        rgroup
        lgroup
        rAngle
        lAngle
        rangle
        langle
        Rbrack
        rBrack
        Lbrack
        lBrack
        cirbot
        bigtop
        bigbot
        veedot
        pencil
        neuter
        swords
        anchor
        dicevi
        diceiv
        diceii
        pisces
        cancer
        Gemini
        gemini
        Taurus
        taurus
        Uranus
        uranus
        Saturn
        saturn
        female
        smiley
        danger
        Square
        square
        boxbar
        CIRCLE
        Circle
        sumtop
        APLlog
        APLinv
        topbot
        inttop
        invnot
        invneg
        rfloor
        lfloor
        niobar
        varnis
        isinvb
        iddots
        nunrhd
        nunlhd
        eqless
        gtrdot
        Supset
        Subset
        rtimes
        ltimes
        bowtie
        bigcup
        bigcap
        bigvee
        barvee
        veebar
        origof
        scurel
        prurel
        nVDash
        nVdash
        nvDash
        nvdash
        Vvdash
        models
        assert
        boxdot
        oslash
        otimes
        ominus
        cupdot
        supset
        subset
        apprge
        gtrsim
        apprle
        nasymp
        nequiv
        measeq
        stareq
        wedgeq
        circeq
        eqcirc
        bumpeq
        Bumpeq
        approx
        nsimeq
        oiiint
        propto
        coprod
        exists
        forall
        mapsto
        mapsup
        MapsUp
        invamp
        daleth
        hslash
        ddddot
        qprime
        fourth
        Exclam
        dprime
        second
        bullet
        dagger
        varrho
        stigma
        Stigma
        varphi
        lambda
        upiota
        upzeta
        upbeta
        Lambda
        upIota
        upZeta
        upBeta
        utilde
        droang
        candra
        ovhook
        spddot
        pounds
        rbrace
        lbrace
        rbrack
        lbrack
        atsign
        period
        rparen
        lparen
        exclam
        nhpar
        vBarv
        DashV
        Dashv
        dashV
        perps
        forks
        forkv
        csupe
        csube
        gescc
        lescc
        simgE
        simlE
        gsiml
        lsimg
        gsime
        lsime
        gtcir
        ltcir
        Equal
        asteq
        eqdot
        nrres
        ndres
        Wedge
        Sqcup
        Sqcap
        amalg
        zpipe
        upint
        sqint
        awint
        tplus
        xbsol
        zhide
        operp
        rblot
        lblot
        Vvert
        psurj
        dicev
        dicei
        sharp
        Libra
        libra
        virgo
        Aries
        aries
        Pluto
        pluto
        earth
        Venus
        skull
        llarc
        lrarc
        urarc
        ularc
        fltns
        strns
        smile
        frown
        rceil
        lceil
        house
        isinE
        barin
        isins
        disin
        ddots
        adots
        cdots
        vdots
        gnsim
        lnsim
        eqgtr
        unrhd
        unlhd
        VDash
        Vdash
        vDash
        dashv
        vdash
        oplus
        sqcup
        sqcap
        uplus
        nsucc
        nprec
        nless
        gneqq
        lneqq
        Equiv
        equiv
        eqdef
        veeeq
        arceq
        Doteq
        doteq
        asymp
        ncong
        nsime
        simeq
        eqsim
        Colon
        oiint
        iiint
        wedge
        angle
        infty
        slash
        minus
        notni
        notin
        nabla
        upand
        gimel
        aleph
        tcohm
        Euler
        DDDot
        dddot
        third
        prime
        ldots
        sampi
        Sampi
        koppa
        qoppa
        Koppa
        Qoppa
        varpi
        upphi
        omega
        uppsi
        upchi
        uptau
        sigma
        uprho
        kappa
        theta
        upeta
        delta
        gamma
        alpha
        Omega
        upPsi
        upChi
        upPhi
        upTau
        Sigma
        upRho
        Theta
        upEta
        Delta
        Gamma
        check
        ocirc
        breve
        times
        tilde
        acute
        grave
        jmath
        imath
        cdotp
        Micro
        sphat
        equal
        colon
        comma
        hline
        bNot
        Perp
        Vbar
        barV
        vBar
        Barv
        mlcp
        csup
        csub
        Succ
        Prec
        late
        smte
        gtcc
        ltcc
        gneq
        lneq
        Same
        eqeq
        rsub
        dsub
        comp
        fcmp
        odiv
        semi
        zcmp
        Join
        intx
        fint
        hide
        xsol
        dsol
        cirE
        obot
        rimg
        limg
        spot
        VERT
        towa
        tosa
        toea
        tona
        finj
        pinj
        psur
        rang
        lang
        upin
        rbag
        Rbag
        lbag
        Lbag
        perp
        flat
        Mars
        male
        XBox
        dres
        rres
        obar
        nisd
        hash
        star
        cdot
        duni
        dint
        odot
        buni
        succ
        prec
        ngeq
        nleq
        ngtr
        geqq
        leqq
        sdef
        cong
        nsim
        oint
        iint
        land
        nmid
        circ
        owns
        nexi
        ffun
        pfun
        Rdsh
        drsh
        Ldsh
        dlsh
        tinj
        tsur
        gets
        Game
        beth
        Finv
        LVec
        lvec
        euro
        Vert
        quad
        uppi
        upxi
        upnu
        upmu
        iota
        zeta
        beta
        upPi
        upXi
        upNu
        upMu
        ring
        DDot
        ddot
        Zbar
        tcmu
        lnot
        cent
        vert
        less
        plus
        Not
        Bot
        Top
        lat
        smt
        gla
        glj
        glE
        lgE
        Vee
        bij
        iff
        Leo
        leo
        sun
        Sun
        lhd
        LHD
        rhd
        RHD
        nis
        ggg
        lll
        Cup
        Cap
        bot
        top
        geq
        leq
        neq
        sim
        int
        cup
        cap
        lor
        vee
        mid
        ast
        QED
        nni
        nin
        exi
        Rsh
        Lsh
        rel
        Yup
        Mho
        mho
        ell
        Vec
        vec
        cat
        phi
        psi
        chi
        tau
        rho
        eta
        Psi
        Phi
        not
        Dot
        dot
        hat
        bar
        div
        eth
        neg
        yen
        \/
        Gt
        Lt
        gg
        ll
        ge
        le
        ne
        wr
        AC
        mp
        ni
        in
        to
        jj
        ii
        ee
        dd
        DD
        Re
        wp
        Im
        pi
        xi
        nu
        mu
        Pi
        Xi
        pm
        :
      ].freeze
      OPERATORS = %w[
        :
        -
        :
        |
        _
        @
        ?
        >
        =
        <
        ;
        .
        +
        ,
        *
        #
        &
        %
        $
        !
      ].freeze
      FONT_STYLES = %w[
        bf
        Bbb
        mtt
        mbf
        mit
        mscr
        msans
        mbfit
        mfrak
        mathit
        mathsf
        mathrm
        mathtt
        mathbb
        mathbf
        mathds
        mbfsans
        mathcal
        mathfrak
        mathbfit
        mathsfbf
        mathsfit
        mathbold
        mbfitsans
        mathsfbfit
      ].freeze
      PARENTHESIS = {
        "[" => "]",
        "{" => "}",
        "(" => ")",
        "\\{" => "\\}",
      }.freeze
      BINARY_CLASSES = %w[
        stackrel
        binom
        frac
        lim
      ].freeze
      UNDEROVER_CLASSES = %w[
        over
        bmod
        pmod
      ].freeze
      POWER_BASE_CLASSES = %w[
        prod
        sum
        inf
        log
      ].freeze
      NUMERIC_VALUES = %w[
        zero
        one
        two
        three
        four
        five
        six
        seven
        eight
        nine
      ].freeze
      MATH_OPERATORS = %w[
        liminf
        arctan
        arcsin
        limsup
        tanh
        coth
        cosh
        sinh
        int
        sin
        max
        dim
        arg
        tan
        sec
        log
        lim
        hom
        det
        cot
        sup
        gcd
        deg
        min
        ker
        exp
        csc
        cos
        Pr
        ln
        lg
      ].freeze
    end
  end
end
