# frozen_string_literal: true

module Plurimath
  class Omml
    class Constants
      TAGS = %w[
        lastRenderedPageBreak
        oMathParaPr
        borderBoxPr
        wrapIndent
        strikeTLBR
        strikeBLTR
        groupChrPr
        wrapRight
        smallFrac
        oMathPara
        hideRight
        brkBinSub
        borderBox
        sSubSupPr
        zeroDesc
        mathFont
        limUppPr
        limLowPr
        hideLeft
        zeroWid
        zeroAsc
        strikeV
        strikeH
        rSpRule
        rMargin
        plcHide
        phantPr
        objDist
        noBreak
        naryLim
        maxDist
        lMargin
        intraSp
        interSp
        hideTop
        hideBot
        eqArrPr
        dispDef
        degHide
        cGpRule
        supHide
        subHide
        vertJc
        transp
        sSupPr
        sSubPr
        sepChr
        postSp
        naryPr
        mathPr
        limUpp
        limLow
        rFonts
        limLoc
        intLim
        funcPr
        endChr
        ctrlPr
        brkBin
        begChr
        baseJc
        alnScr
        sPrePr
        radPr
        preSp
        phant
        opEmu
        oMath
        fName
        eqArr
        defJc
        count
        boxPr
        barPr
        argSz
        argPr
        accPr
        type
        show
        mcPr
        mcJc
        grow
        diff
        sty
        shp
        scr
        rSp
        rPr
        sup
        sub
        pos
        num
        nor
        mPr
        mcs
        lit
        lim
        fPr
        dPr
        den
        deg
        cSp
        chr
        cGp
        brk
        box
        bar
        aln
        mr
        mc
        jc
        t
        i
        m
        e
      ].freeze
      SUB_SUP_TAG = %w[
        groupChr
        sSubSup
        func
        sPre
        sSup
        sSub
        nary
        acc
        rad
        f
        r
        d
      ].freeze
      UNARY_FUNCTIONS = %w[
        arcsin
        arctan
        arccos
        coth
        tanh
        sinh
        cosh
        tan
        cos
        cot
        csc
        sin
        sec
      ].freeze
    end
  end
end
