# frozen_string_literal: true

module Plurimath
  class Omml
    class Constants
      TAGS = %w[
        oMathParaPr
        borderBoxPr
        wrapIndent
        strikeTLBR
        strikeBLTR
        groupChrPr
        wrapRight
        smallFrac
        oMathPara
        hideRight
        brkBinSub
        borderBox
        sSubSupPr
        zeroDesc
        mathFont
        limUppPr
        limLowPr
        hideLeft
        groupChr
        zeroWid
        zeroAsc
        strikeV
        strikeH
        rSpRule
        rMargin
        plcHide
        phantPr
        objDist
        noBreak
        naryLim
        maxDist
        lMargin
        intraSp
        interSp
        hideTop
        hideBot
        eqArrPr
        dispDef
        degHide
        cGpRule
        supHide
        subHide
        vertJc
        transp
        sPrePr
        sSupPr
        sSubPr
        sepChr
        postSp
        naryPr
        mathPr
        limUpp
        limLow
        rFonts
        limLoc
        intLim
        funcPr
        endChr
        ctrlPr
        brkBin
        begChr
        baseJc
        alnScr
        radPr
        preSp
        phant
        opEmu
        oMath
        fName
        eqArr
        defJc
        count
        boxPr
        barPr
        argSz
        argPr
        accPr
        type
        sPre
        show
        nary
        mcPr
        mcJc
        grow
        func
        diff
        sty
        shp
        scr
        rSp
        rPr
        rad
        sup
        sub
        pos
        num
        nor
        mPr
        mcs
        lit
        lim
        fPr
        dPr
        den
        deg
        cSp
        chr
        cGp
        brk
        box
        bar
        aln
        acc
        mr
        mc
        jc
        t
        r
        i
        m
        e
        d
      ].freeze

      SUB_SUP_TAG = %w[
        sSubSup
        sSup
        sSub
        f
      ].freeze
    end
  end
end
