name: gen_docs

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Generate supported_parens_list.adoc
      run: |
        rm -f supported_parens_list.adoc
        bundle exec rake supported_parens_list.adoc

    - name: Generate supported_symbols_list.adoc
      run: |
        rm -f supported_symbols_list.adoc
        bundle exec rake supported_symbols_list.adoc

    - name: Generate Intent-Supported-Classes.adoc
      run: |
        rm -f Intent-Supported-Classes.adoc
        bundle exec rake Intent-Supported-Classes.adoc
