name: Plurimath JS workflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - uses: henrywhitaker3/trigger-external-workflow-action@v1
        with:
          token: ${{ secrets.PLURIMATH_CI_PAT }}
          payload: '{ "workflow_id": "${{ github.run_id }}", "branch": "${{ github.ref }}" }'
          repo: plurimath/plurimath-js
          event: update-submodule
