name: Plurimath JS workflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - uses: plurimath/plurimath-js/.github/workflows/update-submodule.yml@main
      # - uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token: ${{ secrets.PLURIMATH_CI_PAT_TOKEN }}
      #     repository: plurimath/plurimath-js
      #     event-type: update-submodule
      #     client-payload: '{"github": ${{ toJson(github) }}}'
