name: rake

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:

permissions:
  contents: read

jobs:
  rake:
    name: Test on Ruby ${{ matrix.ruby.version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ruby.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        ruby:
          - version: "3.3"
            rubygems: latest
            bundler: default
            experimental: false
          - version: "3.4"
            rubygems: latest
            bundler: default
            experimental: false
          - version: "4.0"
            rubygems: latest
            bundler: default
            experimental: true
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.ruby.version }}-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.PLURIMATH_CI_PAT_TOKEN || github.token }}
          submodules: recursive

      - if: matrix.os == 'windows-latest'
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Configure Bundler
        run: |
          mkdir -p .bundle
          touch .bundle/config
          cat .bundle/config
          echo "---" >> .bundle/config
          echo 'BUNDLE_BUILD__RUBY___LL: "--with-cflags=-std=gnu17"' >> .bundle/config
          cat .bundle/config

      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby.version }}
          rubygems: ${{ matrix.ruby.rubygems }}
          bundler: ${{ matrix.ruby.bundler }}
          bundler-cache: false
          cargo-cache: false
          cache-version: v1

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - run: bundle exec rake
